### ISSUE TITLE
Avoid hardcoding paths and add different configuration files

### ISSUE THREAD

**Issue by javuto** [dan1t0/Rest_Wifi-Pi#5]
Instead of having paths for files hardcoded as strings or other fixed elements, using configuration files can help and will be good to keep maintainability. Format can be just JSON files.

**Comment by dan1t0** [comment]
Added a JSON file config in https://github.com/dan1t0/Rest_Wifi-Pi/commit/7afaea41bb38a0b9bc993fe4efa54aac3abc9957
